datagrid:
    issues-grid:
        options:
            entity_pagination: true

        source:
            type: orm
            query:
                select:
                    - issue
                    - CONCAT(owner.firstName, CONCAT(' ', owner.lastName)) as ownerName
                    - owner.id as ownerId
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterName
                    - reporter.id as reporterId
                    - workflowStep.label as workflowStepLabel
                from:
                    - { table: %orocrm_issue.entity.class%, alias: issue }
                join:
                    left:
                        - { join: issue.priority, alias: priority }
                        - { join: issue.owner, alias: owner }
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.workflowStep, alias: workflowStep }
        columns:
            code:
                label: orocrm.issue.code.label
            summary:
                label: orocrm.issue.summary.label
            type:
                label: orocrm.issue.type.label
            priority:
                label: orocrm.issue.priority.label
            workflowStepLabel:
                label: orocrm.issue.workflow_step.label
            resolution:
                label: orocrm.issue.resolution.label
            reporterName:
                type:          twig
                label:         orocrm.issue.reporter.label
                frontend_type: html
                template:      OroCRMIssueBundle:Datagrid:Columns/owner.html.twig
            ownerName:
                type:          twig
                label:         orocrm.issue.owner.label
                frontend_type: html
                template:      OroCRMIssueBundle:Datagrid:Columns/owner.html.twig
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
        sorters:
            columns:
                code:
                    data_name: issue.code
                summary:
                    data_name: issue.summary
                type:
                    data_name: issue.type
                priority:
                    data_name: priority.order
                workflowStepLabel:
                    data_name: workflowStep.stepOrder
                resolution:
                    data_name: issue.resolution
                ownerName:
                    data_name: ownerName
                reporterName:
                    data_name: reporterName
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                code:
                    type:      string
                    data_name: issue.code
                summary:
                    type:      string
                    data_name: issue.summary
                type:
                    type:      string
                    data_name: issue.type
                priority:
                    type:      string
                    data_name: issue.priority
                workflowStepLabel:
                    type:      entity
                    data_name: issue.workflowStep
                    options:
                        field_type: oro_workflow_step_select
                        field_options:
                            workflow_entity_class: %orocrm_issue.entity.class%
                ownerName:
                    type:      string
                    data_name: ownerName
                reporterName:
                    type:      string
                    data_name: reporterName
                createdAt:
                    type:      datetime
                    data_name: issue.createdAt
                updatedAt:
                    type:      datetime
                    data_name: issue.updatedAt
        properties:
            id: ~
            view_link:
                type:       url
                route:      orocrm_issue_view
                params:
                    - id
            update_link:
                type:       url
                route:      orocrm_issue_update
                params:
                    - id
            delete_link:
                type:       url
                route:      orocrm_api_delete_issue
                params:
                    - id
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link

    issues-children-grid:
        extends: issues-grid
        source:
            query:
                where:
                    and:
                        - issue.parent = :parent
            bind_parameters:
                - parent

    issues-dashboard-grid:
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10
        source:
            type: orm
            query:
                select:
                    - issue
                    - workflowStep.label as workflowStepLabel
                from:
                    - { table: %orocrm_issue.entity.class%, alias: issue }
                join:
                    left:
                        - { join: issue.workflowStep, alias: workflowStep }
                        - { join: issue.collaborators, alias: collaborators }
                where:
                    and:
                        - collaborators.id = :user
                orderBy:
                    - column: issue.updatedAt
                      dir: DESC
            bind_parameters:
                - user
        columns:
            code:
                label: orocrm.issue.code.label
            summary:
                label: orocrm.issue.summary.label
            type:
                label: orocrm.issue.type.label
            priority:
                label: orocrm.issue.priority.label
            workflowStepLabel:
                label: orocrm.issue.workflow_step.label
            resolution:
                label: orocrm.issue.resolution.label
        properties:
            id: ~
            view_link:
                type:       url
                route:      orocrm_issue_view
                params:
                    - id
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
