datagrid:
    issues-grid:
        options:
            entity_pagination: true

        source:
            type: orm
            query:
                select:
                    - issue
                    - CONCAT(owner.firstName, CONCAT(' ', owner.lastName)) as ownerName
                    - owner.id as ownerId
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterName
                    - reporter.id as reporterId
                from:
                    - { table: %orocrm_issue.entity.class%, alias: issue }
                join:
                    left:
                        - { join: issue.priority, alias: priority }
                        - { join: issue.owner, alias: owner }
                        - { join: issue.reporter, alias: reporter }
        columns:
            code:
                label: orocrm.issue.code.label
            summary:
                label: orocrm.issue.summary.label
            priority:
                label: orocrm.issue.priority.label
            reporterName:
                type:          twig
                label:         orocrm.issue.reporter.label
                frontend_type: html
                template:      OroCRMIssueBundle:Datagrid:Columns/owner.html.twig
            ownerName:
                type:          twig
                label:         orocrm.issue.owner.label
                frontend_type: html
                template:      OroCRMIssueBundle:Datagrid:Columns/owner.html.twig
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
        sorters:
            columns:
                code:
                    data_name: issue.code
                summary:
                    data_name: issue.summary
                priority:
                    data_name: priority.order
                ownerName:
                    data_name: ownerName
                reporterName:
                    data_name: reporterName
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                code:
                    type:      string
                    data_name: issue.code
                summary:
                    type:      string
                    data_name: issue.summary
                ownerName:
                    type:      string
                    data_name: ownerName
                reporterName:
                    type:      string
                    data_name: reporterName
                createdAt:
                    type:      datetime
                    data_name: issue.createdAt
                updatedAt:
                    type:      datetime
                    data_name: issue.updatedAt
        properties:
            id: ~
            view_link:
                type:       url
                route:      orocrm_issue_view
                params:
                    - id
            update_link:
                type:       url
                route:      orocrm_issue_update
                params:
                    - id
            delete_link:
                type:       url
                route:      orocrm_issue_delete
                params:
                    - id
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
