parameters:
    orocrm_issue.form.type.issue.class:               OroCRM\Bundle\IssueBundle\Form\Type\IssueType
    orocrm_issue.form.handler.issue.class:            OroCRM\Bundle\IssueBundle\Form\Handler\IssueHandler

services:
    orocrm_issue.form.type.issue:
        class: %orocrm_issue.form.type.issue.class%
        tags:
            - { name: form.type, alias: orocrm_issue }

    orocrm_issue.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'orocrm_issue'
            - 'orocrm_issue'

    orocrm_issue.form.handler.issue:
        class: %orocrm_issue.form.handler.issue.class%
        scope: request
        arguments:
            - @orocrm_issue.form
            - @request
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_tag.tag_manager }
