parameters:
    orocrm_issue.importexport.template_fixture.issue.class: OroCRM\Bundle\IssueBundle\ImportExport\TemplateFixture\IssueFixture

services:
    orocrm_issue.importexport.data_converter:
        parent: oro_importexport.data_converter.configurable

    orocrm_issue.importexport.template_fixture.data_converter.issue:
        parent: oro_importexport.data_converter.template_fixture.configurable

    # Strategy
    orocrm_issue.importexport.strategy.issue.add_or_replace:
        class: %oro_importexport.strategy.configurable_add_or_replace.class%
        parent: oro_importexport.strategy.configurable_add_or_replace

    # Import processor
    orocrm_issue.importexport.processor.import:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, [@orocrm_issue.importexport.data_converter]]
             - [setStrategy, [@orocrm_issue.importexport.strategy.issue.add_or_replace]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %orocrm_issue.entity.class%, alias: orocrm_issue.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: %orocrm_issue.entity.class%, alias: orocrm_issue.add_or_replace }

    # Export processor
    orocrm_issue.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@orocrm_issue.importexport.data_converter]]
        tags:
            - { name: oro_importexport.processor, type: export, entity: %orocrm_issue.entity.class%, alias: orocrm_issue }

    orocrm_issue.importexport.processor.export_template:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@orocrm_issue.importexport.template_fixture.data_converter.issue]]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: %orocrm_issue.entity.class%, alias: orocrm_issue }

    orocrm_issue.importexport.template_fixture.issue:
        class: %orocrm_issue.importexport.template_fixture.issue.class%
        tags:
            - { name: oro_importexport.template_fixture }
