placeholders:
    view_content_data_additional_information:
        items:
            orocrm_issue_children: ~
            orocrm_user_issues: ~

items:
    orocrm_issue_children:
        template: OroCRMIssueBundle:Issue:children.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %orocrm_issue.entity.class%)
    orocrm_user_issues:
        template: OroCRMIssueBundle:Issue:userIssues.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
