OroCRM\Bundle\IssueBundle\Entity\Issue:
    properties:
        code:
            - NotBlank: ~
            - Length:
                max: 255
        summary:
            - NotBlank: ~
            - Length:
                max: 255
        priority:
            - NotBlank: ~
        type:
            - NotBlank: ~
        owner:
            - NotBlank: ~
