parameters:
    acme_demo_grid.user_grid.manager.class: Acme\Bundle\DemoGridBundle\Datagrid\UserDatagridManager
    acme_demo_grid.product_grid.manager.class: Acme\Bundle\DemoGridBundle\Datagrid\ProductDatagridManager
    acme_demo_grid.report_grid.manager.class: Acme\Bundle\DemoGridBundle\Datagrid\ReportDatagridManager

services:
    acme_demo_grid.user_grid.manager:
        class: %acme_demo_grid.user_grid.manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: users
              entity_name: Oro\Bundle\UserBundle\Entity\User
              entity_hint: users
              flexible: true
              route_name: acme_demo_gridbundle_user_list
#              datagrid_builder: ~
#              list_builder: ~
#              query_factory: ~
#              translator: ~
#              validator: ~
#              request: ~

    acme_demo_grid.product_grid.manager:
        class: %acme_demo_grid.product_grid.manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: product
              entity_hint: products
              route_name: acme_demo_gridbundle_product_list
#              query_factory: ~
#              datagrid_builder: ~
#              list_builder: ~
#              translator: ~
#              validator: ~
#              request: ~

    acme_demo_grid.report_grid.manager:
        class: %acme_demo_grid.report_grid.manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: report
              entity_hint: reports
              route_name: acme_demo_gridbundle_report_list
              query_factory: oro_grid.orm.query_factory.report
