orocrm_issue_bundle:
    resource:     "@OroCRMIssueBundle/Controller"
    type:         annotation

orocrm_issue_bundle_api_rest:
    resource:     "@OroCRMIssueBundle/Controller/Api/Rest/IssueController.php"
    type:         rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest
