workflows:
    issue_flow:
        transition_definitions:
            start_progress_definition: ~
            stop_progress_definition: ~
            close_definition: ~
            resolve_definition: ~
            reopen_definition: ~
