entities_config:
    Acme\Bundle\DemoAddressBundle\Entity\SeparateAddress:
        flexible_manager:     oro_address.address.manager.flexible
        flexible_class:       %oro_address.address.service.entity.class%
        flexible_value_class: %oro_address.address.service.entity.value.class%
        flexible_init_mode:   all_attributes
