acme_demo_address_create:
    pattern:  /create
    defaults: { _controller: AcmeDemoAddressBundle:Default:create }

acme_demo_address_edit:
    pattern:  /edit/{id}
    defaults: { _controller: AcmeDemoAddressBundle:Default:edit, id: 0 }
    requirements:
        id: \d+

acme_demo_service_address_create:
    pattern:  /service/create
    defaults: { _controller: AcmeDemoAddressBundle:Separate:create }

acme_demo_service_address_edit:
    pattern:  /service/edit/{id}
    defaults: { _controller: AcmeDemoAddressBundle:Separate:edit, id: 0 }
    requirements:
        id: \d+

acme_demo_address_create_country:
    pattern:  /country/create
    defaults: { _controller: AcmeDemoAddressBundle:Default:createCountry }

acme_demo_address_remove_country:
    pattern:  /country/remove
    defaults: { _controller: AcmeDemoAddressBundle:Default:removeCountry }
