parameters:
    oro_address.address.service.entity.class: Acme\Bundle\DemoAddressBundle\Entity\SeparateAddress
    oro_address.address.service.entity.value.class: Acme\Bundle\DemoAddressBundle\Entity\Value\AddressValue

services:
    oro_address.address.service.manager.flexible:
        class: %oro_address.address.manager.flexible.class%
        arguments:
            - %oro_address.address.service.entity.class%
            - %oro_flexibleentity.flexible_config%
            - @doctrine.orm.entity_manager
            - @event_dispatcher
        tags:
            - { name: oro_flexibleentity_manager, entity: %oro_address.address.service.entity.class%}

    oro_address.address.service.manager:
        class: %oro_address.address.manager.class%
        arguments:
            - %oro_address.address.service.entity.class%
            - @doctrine.orm.entity_manager
            - @oro_address.address.service.manager.flexible
        tags:
            - { name: oro_address.storage, alias: service}
