Acme\Bundle\DemoAddressBundle\Entity\SeparateAddress:
    properties:
        street:
            - NotBlank: ~
            - Length:
                  max: 500
        street2:
            - Length:
                  max: 500
        city:
            - NotBlank: ~
            - Length:
                  max: 255
        state:
            - NotBlank: ~
            - Length:
                  min: 2
                  max: 255
        postalCode:
            - Length:
                  max: 20
        country:
            - NotBlank: ~
            - Length:
                  min: 2
                  max: 70
