js:
  - '@OroUIBundle/Resources/public/lib/jstree/jquery.cookie.js'
  - '@OroUIBundle/Resources/public/lib/jstree/jquery.hotkeys.js'
  - '@OroSegmentationTreeBundle/Resources/public/js/lib/jstree/jquery.jstree.tree_selector.js'

