js:
  - '@AcmeDemoSegmentationTreeBundle/Resources/public/js/jquery.cookie.js'
  - '@AcmeDemoSegmentationTreeBundle/Resources/public/js/jquery.hotkeys.js'
  - '@AcmeDemoSegmentationTreeBundle/Resources/public/js/jquery.jstree.js'