oro_menu_config:
    items:
        demo_segmentation_tree_tab:
            label: 'Segmentation Tree'
            uri: '#'
        demo_segmentation_tree_product:
            label: 'Product Segment'
            route: 'acme_demosegmentationtree_producttree_index'

    tree:
        application_menu:
            children:
                demo_segmentation_tree_tab:
                    children:
                        demo_segmentation_tree_product:
