oro_menu_config:
    items:
        demo_segmentation_tree_tab:
            label: 'Segmentation Tree'
            uri: '#'
            extras:
                routes: ['acme_demosegmentationtree_*']
        demo_segmentation_tree_product:
            label: 'Product Segment'
            route: 'acme_demosegmentationtree_producttree_index'

    tree:
        application_menu:
            children:
                demo_segmentation_tree_tab:
                    children:
                        demo_segmentation_tree_product:

oro_titles:
    acme_demosegmentationtree_producttree_index: Display Index Screen
    oro_user_security_login: Login
    oro_user_reset_request: Forgot Password
    acme_demosegmentationtree_producttree_index: Product Segmentation
