oro_menu_config:
    items:
        demo_workflow_tab:
            label: 'Workflow Demo'
            uri: '#'
            extras:
                routes: ['acme_demoworkflow_*']
        demo_workflow_phonecall:
            label: 'Phone Calls'
            route: 'acme_demoworkflow_phonecall_list'
    tree:
        application_menu:
            children:
                demo_workflow_tab:
                    children:
                        demo_workflow_phonecall: ~
                        demo_workflow_workflowitem: ~

oro_titles:
    acme_demoworkflow_phonecall_list: Phone Calls
    acme_demoworkflow_phonecall_create: Create Phone Call
    acme_demoworkflow_phonecall_edit: Edit Phone Call
    acme_demoworkflow_phonecall_view: View Phone Call
