workflows:
    phone_call:
        label: 'Demo Call Workflow'
        enabled: true
        start_step: start_call
        managed_entity_class: Acme\Bundle\DemoWorkflowBundle\Entity\PhoneCall
        steps:
            start_call:
                label: 'Start Phone Call'
                attributes:
                    - call_timeout
                allowed_transitions:
                    - connected
                    - not_answered
            start_conversation:
                label: 'Call Phone Conversation'
                attributes:
                    - conversation_result
                    - conversation_comment
                    - conversation_successful
                allowed_transitions:
                    - end_conversation
            end_call:
                label: 'End Phone Call'
                is_final: true
        attributes:
            call_timeout:
                form_type: integer
                label: 'Call Timeout'
                options:
                    form_options:
                        required: false
            call_successfull:
                form_type: choice
                label: 'Call Successful'
                options:
                    form_options:
                        choices: {0: 'Yes', 1: 'No'}
                        required: true
                        multiple: false
            conversation_successful:
                form_type: choice
                label: 'Conversation Successful'
                options:
                    form_options:
                        choices: {0: 'Yes', 1: 'No'}
                        required: true
                        multiple: false
            conversation_comment:
                form_type: text
                label: 'Conversation Comment'
            conversation_result:
                form_type: text
                label: 'Conversation Result'
            conversation:
                form_type: entity
                label: 'Conversation'
                options:
                    entity_class: Acme\Bundle\DemoWorkflowBundle\Entity\PhoneConversation
        transitions:
            connected:
                label: 'Connected'
                step_to: start_conversation
                transition_definition: connected_definition
            not_answered:
                label: "Not answered"
                step_to: end_call
                transition_definition: not_answered_definition
            end_conversation:
                label: 'End conversation'
                step_to: end_call
                transition_definition: end_conversation_definition
        transition_definitions:
            connected_definition: # Try to make call connected
                # Check that timeout is set
                conditions:
                    @not_blank: [$call_timeout]
                # Set call_successfull = true
                post_actions:
                    - @assign_value:
                        parameters: [$call_successfull, true]
            not_answered_definition: # Callee did not answer
                # Make sure that caller waited at least 60 seconds
                conditions: # call_timeout not empty and >= 60
                    @and:
                        - @not_blank: [$call_timeout]
                        - @ge: [$call_timeout, 60]
                # Set call_successfull = false
                post_actions:
                    - @assign_value:
                        parameters: [$call_successfull, false]
            end_conversation_definition:
                conditions:
                    # Check required properties are set
                    @and:
                        - @not_blank: [$conversation_result]
                        - @not_blank: [$conversation_comment]
                        - @not_blank: [$conversation_successful]
                # Create PhoneConversation and set it's properties
                # Pass data from workflow to conversation
                post_actions:
                    - @create_entity: # create PhoneConversation
                        parameters:
                            class: Acme\Bundle\DemoWorkflowBundle\Entity\PhoneConversation
                            attribute: $conversation
                            data:
                                result: $conversation_result
                                comment: $conversation_comment
                                successful: $conversation_successful
                                call: $managed_entity
                    - @bind_entity: # bind created PhoneConversation with current workflow item
                        parameters:
                            attribute: $conversation
