imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.yml }
    - { resource: security_test.yml }

framework:
    test: ~

web_profiler:
    toolbar: false

swiftmailer:
    disable_delivery: true
