imports:
    - { resource: parameters.yml }

framework:
    translator:
        fallback:             "%locale%"
    secret:                   "%secret%"
    router:
        resource:             "%kernel.root_dir%/config/routing_install.yml"
        strict_requirements:  "%kernel.debug%"
    form:                     true
    csrf_protection:          false
    validation:
        enable_annotations:   true
    templating:
        engines:              ['twig']
    default_locale:           "%locale%"
    trusted_proxies:          ~
    session:
        name:                 BAPID
        handler_id:           %session_handler%
        save_path:            %kernel.root_dir%/cache/sessions
    fragments:
        enabled:              true
        path:                 /_fragment # used for controller action in template
    serializer:
        enabled:              true

# Twig Configuration
twig:
    debug:                    "%kernel.debug%"
    strict_variables:         "%kernel.debug%"
    form:
        resources:
            - 'OroUIBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:                    false
    use_controller:           false

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:       pdo_mysql
                host:         "%database_host%"
                port:         "%database_port%"
                dbname:       "%database_name%"
                user:         "%database_user%"
                password:     "%database_password%"
                charset:      UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping:         true
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: Oro\Bundle\UserBundle\Entity\User

stof_doctrine_extensions:
    default_locale:           en
    translation_fallback:     true
    orm:
        default:
            translatable:     true
            tree:             true

services:
    oro.cache.abstract:
        abstract:             true
        class:                Doctrine\Common\Cache\PhpFileCache
        arguments:            [%kernel.cache_dir%]
    twig.extension.intl:
         class:               Twig_Extensions_Extension_Intl
         tags:
             - { name: twig.extension }
