acme_demo_flexible_entity:
    resource: "@AcmeDemoFlexibleEntityBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/flexible-entity/
    defaults: { _locale: %locale% }

acme_demo_menu:
    resource: "@AcmeDemoMenuBundle/Controller/"
    type:     annotation
    prefix:   /

acme_demo_measure:
    resource: "@AcmeDemoMeasureBundle/Controller/"
    type:     annotation
    prefix:   /

acme_default:
    pattern:  /{_locale}
    defaults:
        template:    AcmeDemoBundle:Default:index.html.twig
        _locale:     %locale%
        _controller: FrameworkBundle:Template:template
    requirements:
        _locale:  en|fr|de

acme_demo:
    resource: "@AcmeDemoBundle/Controller/"
    type:     annotation

oro_ui:
    resource: "@OroUIBundle/Resources/config/routing.yml"
    prefix:   /ui

oro_user:
    resource: "@OroUserBundle/Resources/config/routing.yml"

oro_search:
    resource: "@OroSearchBundle/Resources/config/routing.yml"
    prefix:   /

oro_soap:
    resource: "@OroSoapBundle/Resources/config/routing.yml"
    prefix:   /api

oro_dataflow:
    resource: "@OroDataFlowBundle/Resources/config/routing.yml"

oro_config:
    resource: "@OroConfigBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
