acme_demo:
    resource: "@AcmeDemoBundle/Controller/"
    type:     annotation

acme_demo_address:
    resource: "@AcmeDemoAddressBundle/Resources/config/routing.yml"
    prefix:   /address

acme_demo_windows:
    resource: "@AcmeDemoWindowsBundle/Resources/config/routing.yml"

acme_demo_segmentation_tree:
    resource: "@AcmeDemoSegmentationTreeBundle/Resources/config/routing.yml"
    prefix:   /segmentation-tree

acme_demo_flexible_entity:
    resource: "@AcmeDemoFlexibleEntityBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/flexible-entity/
    defaults: { _locale: %locale% }

acme_demo_menu:
    resource: "@AcmeDemoMenuBundle/Controller/"
    type:     annotation

acme_demo_measure:
    resource: "@AcmeDemoMeasureBundle/Controller/"
    type:     annotation

acme_demo_grid:
    resource: "@AcmeDemoGridBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/grid/
    defaults: { _locale: %locale% }

acme_demo_filter:
    resource: "@AcmeDemoFilterBundle/Controller/"
    type:     annotation
    prefix:   /filter/

acme_demo_form:
    resource: "@AcmeDemoFormBundle/Controller/"
    type:     annotation
    prefix:   /form/

acme_demo_workflow:
    resource: "@AcmeDemoWorkflowBundle/Controller/"
    type:     annotation
    prefix:   /workflow/

#
# 3rd party routes
#
nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_imagine:
    resource: .
    type:     imagine

_apy_jsformvalidation:
    resource: "@APYJsFormValidationBundle/Resources/config/routing/routing.yml"

#
# ORO routes
#
oro_default:
    pattern:  /
    defaults:
        template:    AcmeDemoBundle:Default:index.html.twig
        _controller: FrameworkBundle:Template:template

oro_assets:
    resource: .
    type:     oro_assetic

oro_auto_routing:
    resource: .
    type:     oro_auto