acme_demo_address:
    resource: "@AcmeDemoAddressBundle/Resources/config/routing.yml"
    prefix:   /address

acme_demo_windows:
    resource: "@AcmeDemoWindowsBundle/Resources/config/routing.yml"
    prefix:   /

acme_demo_segmentation_tree:
    resource:     "@AcmeDemoSegmentationTreeBundle/Resources/config/routing.yml"
    prefix:       /segmentation-tree

acme_demo_flexible_entity:
    resource: "@AcmeDemoFlexibleEntityBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/flexible-entity/
    defaults: { _locale: %locale% }

acme_demo_menu:
    resource: "@AcmeDemoMenuBundle/Controller/"
    type:     annotation
    prefix:   /

acme_demo_measure:
    resource: "@AcmeDemoMeasureBundle/Controller/"
    type:     annotation
    prefix:   /

acme_demo_grid:
    resource: "@AcmeDemoGridBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/grid/
    defaults: { _locale: %locale% }

acme_demo_filter:
    resource: "@AcmeDemoFilterBundle/Controller/"
    type:     annotation
    prefix:   /filter/

acme_demo_form:
    resource: "@AcmeDemoFormBundle/Controller/"
    type:     annotation
    prefix:   /form/

oro_default:
    pattern:  /
    defaults:
        template:    AcmeDemoBundle:Default:index.html.twig
        _controller: FrameworkBundle:Template:template

acme_default:
    pattern:  /
    defaults:
        template:    AcmeDemoBundle:Default:index.html.twig
        _controller: FrameworkBundle:Template:template

acme_demo:
    resource: "@AcmeDemoBundle/Controller/"
    type:     annotation

oro_ui:
    resource: "@OroUIBundle/Resources/config/routing.yml"
    prefix:   /ui

oro_form:
    resource: "@OroFormBundle/Resources/config/routing.yml"
    prefix:   /

oro_notification:
    resource: "@OroNotificationBundle/Resources/config/routing.yml"
    prefix:   /

oro_user:
    resource: "@OroUserBundle/Resources/config/routing.yml"

oro_search:
    resource: "@OroSearchBundle/Resources/config/routing.yml"
    prefix:   /

oro_navigation:
    resource: "@OroNavigationBundle/Resources/config/routing.yml"
    prefix:   /

oro_windows:
    resource: "@OroWindowsBundle/Resources/config/routing.yml"
    prefix: /

oro_soap:
    resource: "@OroSoapBundle/Resources/config/routing.yml"
    prefix:   /api

oro_dataflow:
    resource: "@OroDataFlowBundle/Resources/config/routing.yml"

oro_config:
    resource: "@OroConfigBundle/Resources/config/routing.yml"

oro_dataaudit:
    resource: "@OroDataAuditBundle/Resources/config/routing.yml"

oro_entity_config:
    resource: "@OroEntityConfigBundle/Resources/config/routing.yml"

oro_entity_extend:
    resource: "@OroEntityExtendBundle/Resources/config/routing.yml"

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_imagine:
    resource: .
    type:     imagine

oro_address:
    resource: "@OroAddressBundle/Resources/config/routing.yml"
    prefix:   /

_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"

_apy_jsformvalidation:
    resource: "@APYJsFormValidationBundle/Resources/config/routing/routing.yml"

oro_assets:
    resource: .
    type: oro_assetic

oro_tag:
    resource: "@OroTagBundle/Resources/config/routing.yml"
    prefix:   /
