acme_demo_measure:
    resource: "@AcmeDemoMeasureBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
acme_default:
    pattern:  /{_locale}
    defaults:
        template:    AcmeDemoBundle:Default:index.html.twig
        _locale:     %locale%
        _controller: FrameworkBundle:Template:template
    requirements:
        _locale:  en|fr|de

acme_demo:
    resource: "@AcmeDemoBundle/Controller/"
    type:     annotation

oro_ui:
    resource: "@OroUIBundle/Resources/config/routing.yml"
    prefix:   /ui

oro_user:
    resource: "@OroUserBundle/Resources/config/routing.yml"
    prefix:   /user

oro_search:
    resource: "@OroSearchBundle/Resources/config/routing.yml"
    prefix:   /

oro_soap:
    resource: "@OroSoapBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc