acme_demo:
    resource: "@AcmeDemoBundle/Controller/"
    type:     annotation

acme_demo_address:
    resource: "@AcmeDemoAddressBundle/Resources/config/routing.yml"
    prefix:   /address

acme_demo_windows:
    resource: "@AcmeDemoWindowsBundle/Resources/config/routing.yml"

acme_demo_segmentation_tree:
    resource: "@AcmeDemoSegmentationTreeBundle/Resources/config/routing.yml"
    prefix:   /segmentation-tree

acme_demo_flexible_entity:
    resource: "@AcmeDemoFlexibleEntityBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/flexible-entity/
    defaults: { _locale: %locale% }

acme_demo_menu:
    resource: "@AcmeDemoMenuBundle/Controller/"
    type:     annotation

acme_demo_measure:
    resource: "@AcmeDemoMeasureBundle/Controller/"
    type:     annotation

acme_demo_grid:
    resource: "@AcmeDemoGridBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/grid/
    defaults: { _locale: %locale% }

acme_demo_filter:
    resource: "@AcmeDemoFilterBundle/Controller/"
    type:     annotation
    prefix:   /filter/

acme_demo_form:
    resource: "@AcmeDemoFormBundle/Controller/"
    type:     annotation
    prefix:   /form/

acme_demo_workflow:
    resource: "@AcmeDemoWorkflowBundle/Controller/"
    type:     annotation
    prefix:   /workflow/

#
# 3rd party routes
#
nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_imagine:
    resource: .
    type:     imagine

_apy_jsformvalidation:
    resource: "@APYJsFormValidationBundle/Resources/config/routing/routing.yml"

#
# ORO routes
#
oro_default:
    pattern:  /
    defaults:
        template:    AcmeDemoBundle:Default:index.html.twig
        _controller: FrameworkBundle:Template:template

oro_ui:
    resource: "@OroUIBundle/Resources/config/routing.yml"
    prefix:   /ui

oro_form:
    resource: "@OroFormBundle/Resources/config/routing.yml"

oro_notification:
    resource: "@OroNotificationBundle/Resources/config/routing.yml"

oro_grid:
    resource: "@OroGridBundle/Resources/config/routing.yml"
    prefix:   /

oro_user:
    resource: "@OroUserBundle/Resources/config/routing.yml"

oro_search:
    resource: "@OroSearchBundle/Resources/config/routing.yml"

oro_navigation:
    resource: "@OroNavigationBundle/Resources/config/routing.yml"

oro_windows:
    resource: "@OroWindowsBundle/Resources/config/routing.yml"

oro_soap:
    resource: "@OroSoapBundle/Resources/config/routing.yml"
    prefix:   /api

oro_config:
    resource: "@OroConfigBundle/Resources/config/routing.yml"

oro_dataaudit:
    resource: "@OroDataAuditBundle/Resources/config/routing.yml"

oro_entity:
    resource: "@OroEntityBundle/Resources/config/routing.yml"

oro_entity_config:
    resource: "@OroEntityConfigBundle/Resources/config/routing.yml"

oro_entity_extend:
    resource: "@OroEntityExtendBundle/Resources/config/routing.yml"

oro_workflow:
    resource: "@OroWorkflowBundle/Resources/config/routing.yml"

oro_address:
    resource: "@OroAddressBundle/Resources/config/routing.yml"

oro_translation_bundle:
    resource: "@OroTranslationBundle/Resources/config/routing.yml"

oro_assets:
    resource: .
    type:     oro_assetic

oro_tag:
    resource: "@OroTagBundle/Resources/config/routing.yml"

oro_email:
    resource: "@OroEmailBundle/Resources/config/routing.yml"

oro_organization:
    resource: "@OroOrganizationBundle/Resources/config/routing.yml"

oro_cron:
    resource: "@OroCronBundle/Resources/config/routing.yml"
    prefix:   /cron

oro_installer:
    resource: "@OroInstallerBundle/Resources/config/routing.yml"
