jms_security_extra:
    secure_all_services:                    false
    expressions:                            true

security:
    providers:
        chain_provider:
            chain:
                providers:                  [in_memory, oro_user]
        oro_user:
            id:                             oro_user.security.provider
        in_memory:
            memory:
                users:
                    admin:
                        password:           admin,
                        roles:              ['ROLE_ADMIN']

    encoders:
        Oro\Bundle\UserBundle\Entity\User:  sha512
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern:                        ^/(_(profiler|wdt)|css|images|js)/
            security:                       false

        main:
            pattern:                        ^/
            provider:                       chain_provider
            form_login:
                csrf_provider:              form.csrf_provider
                check_path:                 /user/login-check
                login_path:                 /user/login
            logout:
                path:                       /user/logout
            remember_me:
                key:                        %secret%
                name:                       BAPRM
                lifetime:                   1209600   # stay logged for two weeks
            anonymous:                      true

    access_control:
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
