security:
    firewalls:
        navigationrest:
            pattern:                        ^/api/rest/latest/navigationitems
            provider:                       oro_user
            api:                            false
            http_basic:
                realm: "Secured REST Area"
