jms_security_extra:
    secure_all_services:                    false
    expressions:                            true

security:
    providers:
        chain_provider:
            chain:
                providers:                  [in_memory, oro_user]
        oro_user:
            id:                             oro_user.user_provider
        in_memory:
            memory:
                users:
                    admin:
                        password:           admin,
                        roles:              ['ROLE_ADMIN']

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:                         ROLE_USER
        ROLE_SUPER_ADMIN:                   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:                        ^/(_(profiler|wdt)|css|images|js)/
            security:                       false

        main:
            pattern:                        ^/
            form_login:
                provider:                   chain_provider
                csrf_provider:              form.csrf_provider
                check_path:                 /user/login_check
                login_path:                 /user/login
            logout:
                path:                       /user/logout
            remember_me:
                key:                        %secret%
                name:                       BAPRM
                lifetime:                   1209600   # stay logged for two weeks
            anonymous:                      true

    access_control:
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
