classes:
  - Oro\Bundle\SearchBundle\Controller\Api\SoapController
  - Oro\Bundle\UserBundle\Controller\Api\Soap\UserController
  - Oro\Bundle\UserBundle\Controller\Api\Soap\RoleController
  - Oro\Bundle\UserBundle\Controller\Api\Soap\GroupController
  - Oro\Bundle\AddressBundle\Controller\Api\Soap\AddressController
  - Oro\Bundle\AddressBundle\Controller\Api\Soap\AddressTypeController
  - Oro\Bundle\AddressBundle\Controller\Api\Soap\CountryController
  - Oro\Bundle\AddressBundle\Controller\Api\Soap\RegionController
  - Oro\Bundle\DataAuditBundle\Controller\Api\Soap\AuditController
  - Oro\Bundle\OrganizationBundle\Controller\Api\Soap\BusinessUnitController
