oro_menu_config:
    items:
        homepage:
            name: 'Home page 2'
            translateDomain: 'SomeBundle'
            route: 'oro_menu_index'
        user_registration_register:
            translateDomain: 'SomeBundle'
            route: 'oro_menu_submenu'
        user_profile_show:
            translateDomain: 'menu'
            showNonAuthorized: true
            route: 'oro_menu_submenu'
        user_change_password:
            translateDomain: 'FOSUserBundle'
            label: 'change_password.submit'
            route: 'oro_menu_index'
        test:
            translateDomain: 'FOSUserBundle'
            label: 'change_password.submit'
            uri: 'http://www.google.com'

    tree:
        navbar:
            type: 'navbar'
            extras:
                brand: 'Oro'
                brandLink: '/'
            children:
                user_profile_show:
                    position: 10
                    children:
                        user_change_password: ~
                        test: ~
                homepage:
                    position: 7
                user_registration_register:
                    position: 5
