parameters:
    account.datagrid_manager.class: Acme\Bundle\DemoBundle\Datagrid\AccountDatagridManager

services:
    account.datagrid_manager:
        class: %account.datagrid_manager.class%
        #arguments: [@oro_entity_extend.exted_manager]
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: accounts
              entity_name: Acme\Bundle\DemoBundle\Entity\Account
              query_entity_alias: accounts
              entity_hint: accounts
              route_name: account
