oro_menu_config:
    items:
        demo_ui_tab:
            label: 'UI'
            uri: '#'
        demo_search_tab:
            label: 'Search'
            uri: '#'
        demo_jobs_tab:
            label: 'Jobs'
            uri: '#'
        demo_jobs:
            label: 'Jobs examples'
            route: 'acme_demo_job_index'
        demo_users:
            label: 'Users'
            route: 'oro_user_index'
        demo_roles:
            label: 'Roles'
            route: 'oro_user_role_index'
        demo_groups:
            label: 'Groups'
            route: 'oro_user_group_index'
        demo_search:
            label: 'Advanced search'
            route: 'acme_demo_advanced_search'
        demo_ui:
            label: 'UI Components'
            route: 'oro_ui_index'
        demo_dashboard:
            label: 'Dashboard'
            route: 'acme_default'

        shortcut_jobs:
            label: Jobs List
            route: acme_demo_job_index
            extras:
                description: Create new user instance

    tree:
        application_menu:
            children:
                home:
                    children:
                        demo_dashboard: ~
                demo_ui_tab:
                    children:
                        demo_ui: ~
                demo_search_tab:
                    children:
                        demo_search: ~
                demo_jobs_tab:
                    children:
                        demo_jobs: ~

        shortcuts:
            children:
                shortcut_jobs: ~

oro_titles:
    acme_demo_job_index: Jobs
    acme_demo_job_show: Job "%%command%%" (ID: %%id%%)
    acme_demo_advanced_search: Search
    acme_demo_search_product: %%product.name%%
    acme_demo_create_attribute: Add Attribute
    acme_demo_flexibleproductdemo_edit: Edit Attribute
