oro_menu_config:
    items:
        demo_ui_tab:
            label: 'UI'
            uri: '#'
        demo_search_tab:
            label: 'Search'
            uri: '#'
        demo_users:
            label: 'Users'
            route: 'oro_user_index'
        demo_roles:
            label: 'Roles'
            route: 'oro_user_role_index'
        demo_groups:
            label: 'Groups'
            route: 'oro_user_group_index'
        demo_search:
            label: 'Advanced search'
            route: 'acme_demo_advanced_search'
        demo_ui:
            label: 'UI Components'
            route: 'oro_ui_index'
        demo_dashboard:
            label: 'Dashboard'
            route: 'oro_default'

    tree:
        application_menu:
            children:
                home:
                    children:
                        demo_dashboard: ~
                demo_ui_tab:
                    children:
                        demo_ui: ~
                demo_search_tab:
                    children:
                        demo_search: ~

oro_titles:
    acme_demo_advanced_search: Search
    acme_demo_search_product: %%product.name%%
    acme_demo_create_attribute: Add Attribute
    acme_demo_flexibleproductdemo_edit: Edit Attribute
