Acme\Bundle\DemoBundle\Entity\Product:
    alias: demo_product
    fields:
        -
            name: name
            target_type: text
            target_fields: []
        -
            name: description
            target_type: text
            target_fields: []
        -
            name: price
            target_type: decimal
            target_fields: [price]
        -
            name: count
            target_type: integer
            target_fields: [count]
        -
            name: createDate
            target_type: datetime
            target_fields: [create_date]
        -
            name: manufacturer
            relation_type: many-to-one
            relation_fields:
                -
                    name: name
                    target_type: text
                    target_fields: []
                -
                    name: id
                    target_type: integer
                    target_fields: []
        -
            name: categories
            relation_type: many-to-many
            relation_fields:
                -
                    name: name
                    target_type: text
                    target_fields: [categories]
    flexible_manager: demo_product_manager

Acme\Bundle\DemoBundle\Entity\Customer:
    alias: demo_customer
    fields:
        -
            name: first_name:
            target_type: text
            target_fields: [first_name, all_data]
        -
            name: second_name:
            target_type: text
            target_fields: [second_name, all_data]