parameters:
    demo_wamp_topic_class:          Acme\Bundle\DemoBundle\Wamp\AcmeTopic
    demo_wamp_rpc_class:            Acme\Bundle\DemoBundle\Wamp\AcmeRpc

services:
    acme_demo.wamp.topic_service:
        class:                      %demo_wamp_topic_class%

    acme_demo.wamp.rpc_service:
        class:                      %demo_wamp_rpc_class%

    acme_demo.twig.extension.debug:
        class:        Twig_Extension_Debug
        tags:
             - { name: 'twig.extension' }    
