parameters:
    customer_grid_manager_class:          Acme\Bundle\DemoFlexibleEntityBundle\Datagrid\CustomerDatagridManager
    product_grid_manager_class:           Acme\Bundle\DemoFlexibleEntityBundle\Datagrid\ProductDatagridManager
    customerattribute_grid_manager_class: Acme\Bundle\DemoFlexibleEntityBundle\Datagrid\AttributeDatagridManager
    productattribute_grid_manager_class:  Acme\Bundle\DemoFlexibleEntityBundle\Datagrid\AttributeDatagridManager

services:
    customer_grid_manager:
        class: "%customer_grid_manager_class%"
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: users
              entity_name: Acme\Bundle\DemoFlexibleEntityBundle\Entity\Customer
              entity_hint: customers
              flexible: true
              route_name: acme_demoflexibleentity_customer_list

    product_grid_manager:
        class: "%product_grid_manager_class%"
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: users
              entity_name: Acme\Bundle\DemoFlexibleEntityBundle\Entity\Product
              entity_hint: products
              flexible: true
              route_name: acme_demoflexibleentity_product_list

    customerattribute_grid_manager:
        class: "%customerattribute_grid_manager_class%"
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: attributes
              entity_hint: attributes
              route_name: acme_demoflexibleentity_customerattribute_index
        calls:
            - [ setBaseActionUrl, ["acme_demoflexibleentity_customerattribute"] ]

    productattribute_grid_manager:
        class: "%productattribute_grid_manager_class%"
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: attributes
              entity_hint: attributes
              route_name: acme_demoflexibleentity_productattribute_index
        calls:
            - [ setBaseActionUrl, ["acme_demoflexibleentity_productattribute"] ]


