entities_config:
    Acme\Bundle\DemoFlexibleEntityBundle\Entity\Customer:
        flexible_manager:            customer_manager
        flexible_entity_class:       Acme\Bundle\DemoFlexibleEntityBundle\Entity\Customer
        flexible_entity_value_class: Acme\Bundle\DemoFlexibleEntityBundle\Entity\CustomerAttributeValue
    Acme\Bundle\DemoFlexibleEntityBundle\Entity\Product:
        flexible_manager:                  product_manager
        flexible_entity_class:             Acme\Bundle\DemoFlexibleEntityBundle\Entity\Product
        flexible_entity_value_class:       Acme\Bundle\DemoFlexibleEntityBundle\Entity\ProductAttributeValue
        flexible_attribute_extended_class: Acme\Bundle\DemoFlexibleEntityBundle\Entity\ProductAttribute
