oro_menu_config:
    items:
        demo_flexible_tab:
            label: 'Flexible Entity'
            uri: '#'
        demo_flexible_customer:
            label: 'Customers'
            route: 'acme_demoflexibleentity_customer_list'
        demo_flexible_product:
            label: 'Products'
            route: 'acme_demoflexibleentity_product_list'
        demo_flexible_manufacturer:
            label: 'Manufacturers'
            route: 'acme_demoflexibleentity_manufacturer_index'

    tree:
        application_menu:
            children:
                demo_flexible_tab:
                    children:
                        demo_flexible_config: ~
                        demo_flexible_customer: ~
                        demo_flexible_product: ~
                        demo_flexible_manufacturer: ~
