parameters:
    customer_manager_class:     Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    customer_entity_class:      Acme\Bundle\DemoFlexibleEntityBundle\Entity\Customer
    manufacturer_manager_class: Oro\Bundle\FlexibleEntityBundle\Manager\SimpleManager
    manufacturer_entity_class:  Acme\Bundle\DemoFlexibleEntityBundle\Entity\Manufacturer
    product_manager_class:      Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    product_entity_class:       Acme\Bundle\DemoFlexibleEntityBundle\Entity\Product

services:
    customer_manager:
        class:     "%customer_manager_class%"
        arguments: [%customer_entity_class%, %oro_flexibleentity.flexible_config%, "@doctrine.orm.entity_manager", "@event_dispatcher"]
        tags:
            - { name: oro_flexibleentity_manager, entity: %customer_entity_class%}
    product_manager:
        class:     "%product_manager_class%"
        arguments: [%product_entity_class%, %oro_flexibleentity.flexible_config%, "@doctrine.orm.entity_manager", "@event_dispatcher"]
        tags:
            - { name: oro_flexibleentity_manager, entity: %product_entity_class%}
    manufacturer_manager:
        class:     "%manufacturer_manager_class%"
        arguments: [%manufacturer_entity_class%, "@doctrine.orm.entity_manager"]