parameters:
    customer_manager_class: Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleEntityManager
    customer_entity_class:  Acme\Bundle\DemoFlexibleEntityBundle\Entity\Customer
    manufacturer_manager_class: Oro\Bundle\FlexibleEntityBundle\Manager\SimpleEntityManager
    manufacturer_entity_class:  Acme\Bundle\DemoFlexibleEntityBundle\Entity\Manufacturer
    product_manager_class: Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleEntityManager
    product_entity_class:  Acme\Bundle\DemoFlexibleEntityBundle\Entity\Product

services:
    customer_manager:
        class:     "%customer_manager_class%"
        arguments: [@service_container, %customer_entity_class%]
    manufacturer_manager:
        class:        "%manufacturer_manager_class%"
        arguments:    [@service_container, %manufacturer_entity_class%]
    product_manager:
        class:     "%product_manager_class%"
        arguments: [@service_container, %product_entity_class%]
