parameters:
    customer_manager_class:               Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    customer_entity_class:                Acme\Bundle\DemoFlexibleEntityBundle\Entity\Customer
    manufacturer_manager_class:           Oro\Bundle\FlexibleEntityBundle\Manager\SimpleManager
    manufacturer_entity_class:            Acme\Bundle\DemoFlexibleEntityBundle\Entity\Manufacturer
    product_manager_class:                Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    product_entity_class:                 Acme\Bundle\DemoFlexibleEntityBundle\Entity\Product

services:
    customer_manager:
        class:     "%customer_manager_class%"
        arguments:
            - %customer_entity_class%
            - %oro_flexibleentity.flexible_config%
            - @doctrine.orm.entity_manager
            - @event_dispatcher
            - @oro_flexibleentity.attributetype.factory
        tags:
            - { name: oro_flexibleentity_manager, entity: %customer_entity_class%}
        calls:
            - [ addAttributeType, ['oro_flexibleentity_text'] ]
            - [ addAttributeType, ['oro_flexibleentity_textarea'] ]
            - [ addAttributeType, ['oro_flexibleentity_date'] ]
            - [ addAttributeType, ['oro_flexibleentity_url'] ]
            - [ addAttributeType, ['oro_flexibleentity_money'] ]
            - [ addAttributeType, ['oro_flexibleentity_simpleselect'] ]
            - [ addAttributeType, ['oro_flexibleentity_multiselect'] ]

    product_manager:
        class:     "%product_manager_class%"
        arguments:
            - %product_entity_class%
            - %oro_flexibleentity.flexible_config%
            - @doctrine.orm.entity_manager
            - @event_dispatcher
            - @oro_flexibleentity.attributetype.factory
        tags:
            - { name: oro_flexibleentity_manager, entity: %product_entity_class%}
        calls:
            - [ addAttributeType, ['oro_flexibleentity_text'] ]
            - [ addAttributeType, ['oro_flexibleentity_textarea'] ]
            - [ addAttributeType, ['oro_flexibleentity_date'] ]
            - [ addAttributeType, ['oro_flexibleentity_metric'] ]
            - [ addAttributeType, ['oro_flexibleentity_price'] ]
            - [ addAttributeType, ['oro_flexibleentity_simpleselect'] ]
            - [ addAttributeType, ['oro_flexibleentity_multiselect'] ]

    manufacturer_manager:
        class:     "%manufacturer_manager_class%"
        arguments: [%manufacturer_entity_class%, "@doctrine.orm.entity_manager"]

    form.type.acme_product:
        class: Acme\Bundle\DemoFlexibleEntityBundle\Form\Type\ProductType
        arguments: [@product_manager, 'acme_product_value']
        tags:
            - { name: form.type, alias: acme_product }

    form.type.acme_product_value:
        class: Acme\Bundle\DemoFlexibleEntityBundle\Form\Type\ProductValueType
        arguments: [@product_manager]
        tags:
            - { name: form.type, alias: acme_product_value }

    form.type.acme_customer:
        class: Acme\Bundle\DemoFlexibleEntityBundle\Form\Type\CustomerType
        arguments: [@customer_manager, 'acme_customer_value']
        tags:
            - { name: form.type, alias: acme_customer }

    form.type.acme_customer_value:
        class: Acme\Bundle\DemoFlexibleEntityBundle\Form\Type\CustomerValueType
        arguments: [@customer_manager]
        tags:
            - { name: form.type, alias: acme_customer_value }


