Acme\Bundle\DemoSearchBundle\Entity\Item:
    label: Demo Search bundle item
    alias: demoSearchBundle:Item
    route:
        name: oro_search_results
    fields:
        -
            name: stringValue
            target_type: text
            target_fields: [stringValue, all_data]
        -
            name: integerValue
            target_type: integer
            target_fields: [integerValue, all_data]
        -
            name: decimalValue
            target_type: decimal
            target_fields: [decimalValue, all_data]
        -
            name: floatValue
            target_type: decimal
            target_fields: [floatValue, all_data]
        -
            name: datetimeValue
            target_type: datetime
            target_fields: [datetimeValue, all_data]
        -
            name: blobValue
            target_type: text
            target_fields: [blobValue, all_data]

#Acme\Bundle\DemoFlexibleEntityBundle\Entity\Product:
#     alias: demo_flexible_product
#     label: Demo Products
#     flexible_manager: product_manager
#     route:
#         name: acme_demo_search_product
#         parameters:
#             id: id
#     title_fields: [sku]
#     fields:
#         -
#            name: sku
#            target_type: text
#            target_fields: [sku, all_data]
#
#Acme\Bundle\DemoFlexibleEntityBundle\Entity\Customer:
#     alias: demo_flexible_customer
#     label: Demo Customers
#     flexible_manager: customer_manager
#     route:
#         name: oro_search
#         parameters:
#             id: id
#     title_fields: [lastname,firstname]
#     fields:
#         -
#            name: email
#            target_type: text
#            target_fields: [email, all_data]
#         -
#            name: firstname
#            target_type: text
#            target_fields: [firstname, all_data]
#         -
#            name: lastname
#            target_type: text
#            target_fields: [lastname, all_data]
#
#Acme\Bundle\DemoBundle\Entity\Product:
#    alias: demo_product
#    flexible_manager: demo_product_manager
#    label: Demo products
#    route:
#        name: acme_demo_search_product
#        parameters:
#            id: id
#    title_fields: [name]
#    search_template: AcmeDemoBundle:Search:demoProductResult.html.twig
#    fields:
#        -
#            name: name
#            target_type: text
#        -
#            name: description
#            target_type: text
#        -
#            name: price
#            target_type: decimal
#            target_fields: [price]
#        -
#            name: count
#            target_type: integer
#            target_fields: [count]
#        -
#            name: createDate
#            target_type: datetime
#            target_fields: [create_date]
#        -
#            name: manufacturer
#            relation_type: many-to-one
#            relation_fields:
#                -
#                    name: name
#                    target_type: text
#                -
#                    name: id
#                    target_type: integer
#        -
#            name: categories
#            relation_type: many-to-many
#            relation_fields:
#                -
#                    name: name
#                    target_type: text
#                    target_fields: [categories]
#
#Acme\Bundle\DemoBundle\Entity\Customer:
#    alias: demo_customer
#    label: Demo customer
#    title_fields: [firstName, lastName]
#    route:
#        name: oro_search
#        parameters:
#            id: id
#    fields:
#        -
#            name: firstName
#            target_type: text
#            target_fields: [name]
#        -
#            name: lastName
#            target_type: text
#            target_fields: [name]
#        -
#            name: city
#            target_type: text
