Acme\Bundle\DemoSearchBundle\Entity\Item:
    fields:
        -
            name: stringValue
            target_type: text
            target_fields: [stringValue, all_data]
        -
            name: integerValue
            target_type: integer
            target_fields: [integerValue, all_data]
        -
            name: decimalValue
            target_type: decimal
            target_fields: [decimalValue, all_data]
        -
            name: floatValue
            target_type: decimal
            target_fields: [floatValue, all_data]
        -
            name: datetimeValue
            target_type: datetime
            target_fields: [datetimeValue, all_data]
        -
            name: blobValue
            target_type: text
            target_fields: [blobValue, all_data]

Acme\Bundle\DemoFlexibleEntityBundle\Entity\Product:
    fields:
        -
            name: sku
            target_type: text
            target_fields: [sku, all_data]
    flexible_manager: product_manager