Acme\Bundle\DemoSearchBundle\Entity\Item:
    label: Demo Search bundle item
    alias: demoSearchBundle:Item
    route:
        name: acme_demo_search
    fields:
        -
            name: stringValue
            target_type: text
            target_fields: [stringValue, all_data]
        -
            name: integerValue
            target_type: integer
            target_fields: [integerValue, all_data]
        -
            name: decimalValue
            target_type: decimal
            target_fields: [decimalValue, all_data]
        -
            name: floatValue
            target_type: decimal
            target_fields: [floatValue, all_data]
        -
            name: datetimeValue
            target_type: datetime
            target_fields: [datetimeValue, all_data]
        -
            name: blobValue
            target_type: text
            target_fields: [blobValue, all_data]

Acme\Bundle\DemoFlexibleEntityBundle\Entity\Product:
     alias: demo_flexible_product
     flexible_manager: product_manager
     label: Demo Products
     route:
         name: acme_demo_search_product
         parameters:
             id: id
     title_fields: [sku]
     fields:
         -
            name: sku
            target_type: text
            target_fields: [sku, all_data]
     flexible_manager: product_manager
