parameters:
    search_item_manager_class:     Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    search_item_entity_class:      Acme\Bundle\DemoSearchBundle\Entity\Item
services:
    search_item_manager:
        class:     "%search_item_manager_class%"
        arguments: [@service_container, %search_item_entity_class%]
