parameters:
    search_item_manager_class:    Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    search_item_entity_class:     Acme\Bundle\DemoSearchBundle\Entity\Item
#    manufacturer_manager_class:   Oro\Bundle\FlexibleEntityBundle\Manager\SimpleManager
#    manufacturer_entity_class:    Acme\Bundle\DemoFlexibleEntityBundle\Entity\Manufacturer
#    product_manager_class:        Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
#    product_entity_class:         Acme\Bundle\DemoFlexibleEntityBundle\Entity\Product

services:
    search_item_manager:
        class:     "%search_item_manager_class%"
        arguments: [%search_item_entity_class%, %oro_flexibleentity.flexible_config%, "@doctrine.orm.entity_manager", "@event_dispatcher", "@oro_flexibleentity.attributetype.factory"]
 #   manufacturer_manager:
 #       class:     "%manufacturer_manager_class%"
 #       arguments: [%manufacturer_entity_class%, "@doctrine.orm.entity_manager"]
 #   product_manager:
 #       class:     "%product_manager_class%"
 #       arguments: [%product_entity_class%, %oro_flexibleentity.flexible_config%, "@doctrine.orm.entity_manager", "@event_dispatcher"]