connector:
    database:
        host:                 127.0.0.1
        dbname:               magento_ab
        user:                 root
        password:             root
    table_prefix:         ab_
