services:
    connector.magento_catalog:
        class: Acme\Bundle\DemoDataFlowBundle\Connector\MagentoConnector
        arguments: [ @product_manager ]
        tags:
            - { name: oro_dataflow_connector }

    job.import_attributes:
        class: Acme\Bundle\DemoDataFlowBundle\Connector\ImportAttributesJob
        arguments: [ @product_manager ]

