parameters:

    connector.magento_catalog:               Acme\Bundle\DemoDataFlowBundle\Connector\MagentoConnector
    connector.type.magento_catalog.class:    Acme\Bundle\DemoDataFlowBundle\Form\Type\MagentoConnectorType

    connector.csv:                           Acme\Bundle\DemoDataFlowBundle\Connector\CsvConnector
    connector.type.csv.class:                Acme\Bundle\DemoDataFlowBundle\Form\Type\CsvConnectorType

    connector.type.import_attribute.class:   Acme\Bundle\DemoDataFlowBundle\Form\Type\ImportAttributeType

services:

    # connector Magento and related form type
    
    connector.magento_catalog:
        class: Acme\Bundle\DemoDataFlowBundle\Connector\MagentoConnector

    connector.form.magento_catalog:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["connector_magento_catalog_form", "connector_magento_catalog"]

    connector.form.type.magento_catalog:
        class: %connector.type.magento_catalog.class%
        tags:
            - { name: form.type, alias: connector_magento_catalog}

    # job import attributes

    job.import_attributes:
        class: Acme\Bundle\DemoDataFlowBundle\Job\ImportAttributesJob
        arguments: [ @product_manager ]
        tags:
            - { name: oro_dataflow_job, connector: connector.magento_catalog}

    connector.form.import_attribute:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["connector_import_attribute_form", "import_attribute"]

    connector.form.type.import_attribute:
        class: %connector.type.import_attribute.class%
        tags:
            - { name: form.type, alias: import_attribute}

    # connector csv

    connector.csv:
        class: Acme\Bundle\DemoDataFlowBundle\Connector\CsvConnector

    connector.form.csv:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["connector_csv_form", "connector_csv"]

    connector.form.type.csv:
        class: %connector.type.csv.class%
        tags:
            - { name: form.type, alias: connector_csv}

    # job import customer
    
    job.import_customers:
        class: Acme\Bundle\DemoDataFlowBundle\Job\ImportCustomersJob
        arguments: [ @customer_manager ]
        tags:
            - { name: oro_dataflow_job, connector: connector.csv }
