parameters:
    dataflow_connector.chain.class: Oro\Bundle\DataFlowBundle\Connector\ConnectorChain

services:
    dataflow_connector.chain:
        class: "%dataflow_connector.chain.class%"

    connector.magento:
        class: Acme\Bundle\DemoDataFlowBundle\Connector\MagentoConnector
        arguments: [ @product_manager ]
        tags:
            - { name: dataflow_connector }
        

    job.import_attributes:
        class: Acme\Bundle\DemoDataFlowBundle\Job\ImportAttributes
        arguments: [ @product_manager ]
        tags:
            - { name: dataflow_job }
    
    