services:
    connector.magento:
        class: Acme\Bundle\DemoDataFlowBundle\Connector\MagentoConnector
        arguments: [ @product_manager ]
        tags:
            - { name: dataflow_connector }

    job.import_attributes:
        class: Acme\Bundle\DemoDataFlowBundle\Job\ImportAttributesJob
        arguments: [ @product_manager ]
        tags:
            - { name: dataflow_job }
