parameters:

    connector.magento_catalog.class:           Acme\Bundle\DemoDataFlowBundle\Connector\MagentoConnector
    configuration.magento_catalog.class:       Acme\Bundle\DemoDataFlowBundle\Configuration\MagentoConfiguration
    configuration.type.magento_catalog.class:  Acme\Bundle\DemoDataFlowBundle\Form\Type\MagentoConnectorType

    connector.csv.class:                       Acme\Bundle\DemoDataFlowBundle\Connector\CsvConnector
    configuration.csv.class:                   Acme\Bundle\DemoDataFlowBundle\Configuration\CsvConfiguration
    configuration.type.csv.class:              Acme\Bundle\DemoDataFlowBundle\Form\Type\CsvConnectorType
    
    job.type.import_attribute.class:           Acme\Bundle\DemoDataFlowBundle\Job\ImportAttributesJob
    configuration.import_attribute.class:      Acme\Bundle\DemoDataFlowBundle\Configuration\ImportAttributeConfiguration
    configuration.type.import_attribute.class: Acme\Bundle\DemoDataFlowBundle\Form\Type\ImportAttributeType

    job.type.import_customer.class:            Acme\Bundle\DemoDataFlowBundle\Job\ImportCustomersJob
    configuration.import_customer.class:       Acme\Bundle\DemoDataFlowBundle\Configuration\ImportCustomerConfiguration
    configuration.type.import_customer.class:  Acme\Bundle\DemoDataFlowBundle\Form\Type\ImportCustomerType

services:

    # connector Magento and related form type
    
    connector.magento_catalog:
        class: %connector.magento_catalog.class%
        arguments: [%configuration.magento_catalog.class%]

    configuration.form.magento_catalog:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["configuration_magento_catalog_form", "configuration_magento_catalog"]

    configuration.form.type.magento_catalog:
        class: %configuration.type.magento_catalog.class%
        tags:
            - { name: form.type, alias: configuration_magento_catalog}

    # job import attributes

    job.import_attributes:
        class: %job.type.import_attribute.class%
        arguments: [%configuration.magento_catalog.class%, %configuration.import_attribute.class%, @product_manager ]
        tags:
            - { name: oro_dataflow_job, connector: connector.magento_catalog}

    configuration.form.import_attribute:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["configuration_import_attribute_form", "import_attribute"]

    configuration.form.type.import_attribute:
        class: %configuration.type.import_attribute.class%
        tags:
            - { name: form.type, alias: import_attribute}

    # connector csv

    connector.csv:
        class: %connector.csv.class%
        arguments: [%configuration.csv.class%]

    configuration.form.csv:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["configuration_csv_form", "configuration_csv"]

    configuration.form.type.csv:
        class: %configuration.type.csv.class%
        tags:
            - { name: form.type, alias: configuration_csv}

    # job import customer
    
    job.import_customers:
        class: %job.type.import_customer.class%
        arguments: [%configuration.csv.class%, %configuration.import_customer.class%, @customer_manager]
        tags:
            - { name: oro_dataflow_job, connector: connector.csv }

    configuration.form.import_customer:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["configuration_import_customer_form", "configuration_import_customer"]

    configuration.form.type.import_customer:
        class: %configuration.type.import_customer.class%
        tags:
            - { name: form.type, alias: configuration_import_customer}
