measures_config:
    Capacitance:
        standard: FARAD
        units:
            FARAD:
                convert: [{'mul': 1}]
                symbol: F
            KILOFARAD:
                convert: [{'mul': 1000}]
                symbol: kF
            MEGAFARAD:
                convert: [{'mul': 1000000}]
                symbol: MF
    Length:
        standard: METER
        units:
            DONG:
                convert: [{'mul': 7},{'div': 300}]
                symbol: dong